CREATE TABLE [METRIX].[ExportType]
(
	[ExportTypeID] TINYINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Description varchar(150) NOT NULL,
	ImportTypeID TINYINT NULL FOREIGN KEY REFERENCES METRIX.ImportType(ImportTypeID) ON UPDATE CASCADE ON DELETE SET NULL
)