//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Data.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttemptFailure
    {
        public int LoginAttemptFailureID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public System.DateTime LoginAttemptDateTime { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DC { get; set; }
    }
}
