//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Data.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountSession
    {
        public System.Guid SG { get; set; }
        public short UserID { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LastActionDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
        public Nullable<bool> WasForcedLogout { get; set; }
        public int RV { get; set; }
        public System.DateTime LU { get; set; }
        public System.DateTime DC { get; set; }
        public Nullable<System.DateTime> DD { get; set; }
    
        public virtual User User { get; set; }
    }
}
