//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Data.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public short UserRoleID { get; set; }
        public short UserID { get; set; }
        public short RoleID { get; set; }
        public System.DateTime DC { get; set; }
        public short UIDC { get; set; }
        public System.DateTime LU { get; set; }
        public short UILU { get; set; }
        public int Status { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
