CREATE VIEW [UTIL].[vw_Default_Constraints]
AS
SELECT
	d.Name,
	d.OBJECT_ID,
	QUOTENAME(SCHEMA_NAME(SCHEMA_ID)) + '.' + QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID)) [PARENT_OBJECT],
	COL_NAME(PARENT_OBJECT_ID, PARENT_COLUMN_ID) [PARENT_COLUMN],
	PARENT_COLUMN_ID, 
	PARENT_OBJECT_ID,
	Create_Date, Modify_Date,	
	[DropStatement] = 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(SCHEMA_ID)) + '.' + QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID)) + ' DROP CONSTRAINT ' + QUOTENAME(d.name) + '
GO',
	[CreateStatement] = 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(SCHEMA_ID)) + '.' + QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID))  + ' ADD CONSTRAINT ' + QUOTENAME(d.Name)
	+ ' DEFAULT ' + [definition] + ' FOR ' + QUOTENAME(COL_NAME(PARENT_OBJECT_ID, PARENT_COLUMN_ID)) + '
GO',
	d.[Definition]
FROM sys.default_constraints d