CREATE VIEW  UTIL.vw_ForeignKeys_Check
AS
SELECT [CheckScript] = 'IF EXISTS(SELECT null FROM ' + QUOTENAME(OBJECT_SCHEMA_NAME(PARENT_OBJECT_ID)) + '.' 
				+ QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID)) + ' WITH (NOLOCK) WHERE [' + REPLACE(PARENT_COLUMNS, ',', '] = ?? AND [') + '] = ??)
	SELECT COUNT(*) as [' + ForeignKey + '] FROM ' + QUOTENAME(OBJECT_SCHEMA_NAME(PARENT_OBJECT_ID)) + '.' 
				+ QUOTENAME(OBJECT_NAME(PARENT_OBJECT_ID)) + ' WITH (NOLOCK) WHERE [' + REPLACE(PARENT_COLUMNS, ',', '] = ?? AND [') + '] = ??', * 
FROM UTIL.vw_ForeignKeys