CREATE TABLE [Security].[Role]
(
	[RoleID] SMALLINT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RoleName] VARCHAR(50) NOT NULL,
	[DC] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [UIDC] SMALLINT NOT NULL, 
    [LU] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [UILU] SMALLINT NOT NULL, 
    [Status] INT NOT NULL DEFAULT (1), 
	
CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([RoleID] ASC),
CONSTRAINT [FK_Role_User_Uidc] FOREIGN KEY ([UIDC]) REFERENCES [Security].[User] ([UserID]),
CONSTRAINT [FK_Role_User_Uilu] FOREIGN KEY ([UILU]) REFERENCES [Security].[User]([UserID])
)



