CREATE TABLE [Security].[UserRole]
(
	[UserRoleID] SMALLINT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[UserID] SMALLINT NOT NULL,
	[RoleID] SMALLINT NOT NULL,
	[DC] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [UIDC] SMALLINT NOT NULL, 
    [LU] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [UILU] SMALLINT NOT NULL, 
    [Status] INT NOT NULL DEFAULT (1),

    CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED ([UserRoleID] ASC),
	CONSTRAINT [FK_UserRole_UserID] FOREIGN KEY ([UserID]) REFERENCES [Security].[User] ([UserID]),
	CONSTRAINT [FK_UserRole_Role] FOREIGN KEY ([RoleID]) REFERENCES [Security].[Role] ([RoleID]),
	CONSTRAINT [FK_UserRole_User_Uidc] FOREIGN KEY ([UIDC]) REFERENCES [Security].[User] ([UserID]),
	CONSTRAINT [FK_UserRole_User_Uilu] FOREIGN KEY ([UILU]) REFERENCES [Security].[User] ([UserID]),

	CONSTRAINT [IX_UserRole] UNIQUE NONCLUSTERED 
	(
		[UserID] ASC,
		[RoleID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
)


