using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SEIDR;

namespace JobUnitTest.FileSplitting
{
    [TestClass]
    public class LexisNexisParseJob: JobTestBase<SEIDR.FileSystem.FileSplitting.LexisNexisParseJob>
    {

        void TestParse(string FileName, bool success, int facilityCount = 0)
        {
            if (success)
                SetExecutionTestFile(FileName, nameof(FileSplitting));
            else
                _TestExecution.FilePath = FileName;
            Assert.AreEqual(success, ExecuteTest());
            if (success)
            {
                var check = MyRoot.GetFiles("*.CYM");
                Assert.AreEqual(facilityCount, check.Length);
                foreach (FileInfo fi in check)
                {
                    AssertFileContent(fi.Name, fi, true, nameof(FileSplitting));
                }

            }
        }

        [TestMethod]
        public void TestParseSmall()
        {
            //Dummy file generated by random replacement from original.
            TestParse("LexisNexisBatchFile_994_20190801_030114__out.csv", true, 2);
        }
        [TestMethod]
        public void TestParseLarge()
        {
            TestParse("LexisNexisBatchFile_994_20190802_030114__out.csv", true, 5);
        }

        [TestMethod]
        public void TestNullPath()
        {
            TestParse(null, false);
        }
        [TestMethod]
        public void TestInvalidPath()
        {
            TestParse("C:\\NONEXISTENT.TXT", false);
        }

    }
}
